// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellSphere.Core;

#nullable disable

namespace SellSphere.Core.Migrations
{
    [DbContext(typeof(SellSphereContext))]
    [Migration("20231101115342_123")]
    partial class _123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f21435b4-45fd-46fe-96e9-0ac70646b56b",
                            ConcurrencyStamp = "f253d8b6-0b45-43c8-bcce-c715c516233d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d8bf4223-e9ae-46f3-9e1f-0c8351541bef",
                            ConcurrencyStamp = "06caf02c-424f-4a67-9894-73e249a2004e",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "64aaf16e-fc7a-4935-add1-159d91dc358e",
                            ConcurrencyStamp = "919383c7-1866-4c20-bb02-ca99b7f62476",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c87d8aab-8143-494b-b960-9258c5335af8",
                            RoleId = "f21435b4-45fd-46fe-96e9-0ac70646b56b"
                        },
                        new
                        {
                            UserId = "c87d8aab-8143-494b-b960-9258c5335af8",
                            RoleId = "d8bf4223-e9ae-46f3-9e1f-0c8351541bef"
                        },
                        new
                        {
                            UserId = "c87d8aab-8143-494b-b960-9258c5335af8",
                            RoleId = "64aaf16e-fc7a-4935-add1-159d91dc358e"
                        },
                        new
                        {
                            UserId = "9678a73a-87ec-4fed-8188-60657e818ac5",
                            RoleId = "d8bf4223-e9ae-46f3-9e1f-0c8351541bef"
                        },
                        new
                        {
                            UserId = "9678a73a-87ec-4fed-8188-60657e818ac5",
                            RoleId = "64aaf16e-fc7a-4935-add1-159d91dc358e"
                        },
                        new
                        {
                            UserId = "09bfa055-bfbc-43c1-a90d-b1aed8e4b5c8",
                            RoleId = "64aaf16e-fc7a-4935-add1-159d91dc358e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SellSphere.Core.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"), 1L, 1);

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityName = "Приватний"
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityName = "Бізнес"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Тварини"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Електроніка"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Бізнес та послуги"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Хобі, відпочинок і спорт"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Дім та сад"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Дитячий світ"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Мода і стиль"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Condition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"), 1L, 1);

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConditionId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            ConditionId = 1,
                            ConditionName = "Новий"
                        },
                        new
                        {
                            ConditionId = 2,
                            ConditionName = "Б/У"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"), 1L, 1);

                    b.Property<string>("DeliveryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            DeliveryName = "Нова Пошта"
                        },
                        new
                        {
                            DeliveryId = 2,
                            DeliveryName = "Укрпошта"
                        },
                        new
                        {
                            DeliveryId = 3,
                            DeliveryName = "Meest"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Goods", b =>
                {
                    b.Property<int>("GoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsId"), 1L, 1);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GoodsId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Goodes");

                    b.HasData(
                        new
                        {
                            GoodsId = 1,
                            ActivityId = 1,
                            CategoryId = 2,
                            ConditionId = 2,
                            DeliveryId = 1,
                            Description = "ноутбук в гарному стані, є невеликі подряпини, екран не битий, 15.6 дюймів",
                            GoodsName = "Ноутбук",
                            ImgPath = "\\Images\\acer.jpg",
                            LocationId = 1,
                            PhoneNumber = "0685894567",
                            Price = 35440,
                            PublicationDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "09bfa055-bfbc-43c1-a90d-b1aed8e4b5c8"
                        },
                        new
                        {
                            GoodsId = 2,
                            ActivityId = 1,
                            CategoryId = 4,
                            ConditionId = 2,
                            DeliveryId = 1,
                            Description = "Велосипед використовувався 1 рік, є незначні пошкодженння, ТО робилося кожних 200 км",
                            GoodsName = "Велосипед",
                            ImgPath = "\\Images\\velik.jpg",
                            LocationId = 3,
                            PhoneNumber = "0975894567",
                            Price = 66700,
                            PublicationDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "09bfa055-bfbc-43c1-a90d-b1aed8e4b5c8"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Чернігів"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Київ"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Луцьк"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Житомир"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Рівне"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c87d8aab-8143-494b-b960-9258c5335af8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "855c0705-0853-4726-b419-8903205ae2f2",
                            Email = "admin@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SELLSPHERE.COM",
                            NormalizedUserName = "ADMIN@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPe+8DAHrWG0oSAhQMfz0XXxuqXb5IHDtXNCJYuNU1AiH3N59n0DCTynmET62/ecZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4a595b9-eba7-4728-9c07-27f1b83d09f4",
                            TwoFactorEnabled = false,
                            UserName = "admin@sellsphere.com"
                        },
                        new
                        {
                            Id = "9678a73a-87ec-4fed-8188-60657e818ac5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a260eff4-0cf8-4528-b880-67d28939f91a",
                            Email = "moder@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODER@SELLSPHERE.COM",
                            NormalizedUserName = "MODER@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEM6NyK5hGy3BmIwKA3o/yq+jhVI/H0H1Bndt0OeGi45Dw9R6KNGAm2aEP8kIvoJ4g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e56aaae6-d256-4792-93e6-dbc791efb250",
                            TwoFactorEnabled = false,
                            UserName = "moder@sellsphere.com"
                        },
                        new
                        {
                            Id = "09bfa055-bfbc-43c1-a90d-b1aed8e4b5c8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3990afc9-c7b5-4274-b61d-8746855dd4e6",
                            Email = "user@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@SELLSPHERE.COM",
                            NormalizedUserName = "USER@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEEFtZ5ijKEWG3uqKLBDcmJcr4Ige07gDMIt0axSh7PXmnOxqonK9bte9MCIpwmr/Pg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "58097dcb-1e87-43fd-b6b6-3fe6a17707cc",
                            TwoFactorEnabled = false,
                            UserName = "user@sellsphere.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellSphere.Core.Goods", b =>
                {
                    b.HasOne("SellSphere.Core.Activity", "Activity")
                        .WithMany("Goods")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Category", "Category")
                        .WithMany("Goodes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Condition", "Condition")
                        .WithMany("Goods")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Delivery", "Delivery")
                        .WithMany("Goods")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Location", "Location")
                        .WithMany("Goods")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.User", "User")
                        .WithMany("Goodes")
                        .HasForeignKey("UserId");

                    b.Navigation("Activity");

                    b.Navigation("Category");

                    b.Navigation("Condition");

                    b.Navigation("Delivery");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SellSphere.Core.Activity", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Category", b =>
                {
                    b.Navigation("Goodes");
                });

            modelBuilder.Entity("SellSphere.Core.Condition", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Delivery", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Location", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.User", b =>
                {
                    b.Navigation("Goodes");
                });
#pragma warning restore 612, 618
        }
    }
}
