// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellSphere.Core;

#nullable disable

namespace SellSphere.Core.Migrations
{
    [DbContext(typeof(SellSphereDbContext))]
    [Migration("20230915203311_etyi")]
    partial class etyi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "41ba8efb-917d-4827-b7a9-2b9ca88324cb",
                            ConcurrencyStamp = "34def90f-1566-455f-aed7-23ecdb26d356",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "eea06f46-65c6-4b64-a57a-4e36d846c462",
                            ConcurrencyStamp = "eb94e341-90d1-4be1-9f29-e87daa807484",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "8bc01d01-b833-4304-bdda-10da6e453715",
                            ConcurrencyStamp = "8fc5c82a-7df2-4053-9302-ce9c66ddd7ec",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "c145bd0d-9ff1-41ce-a54b-2756033b5233",
                            RoleId = "41ba8efb-917d-4827-b7a9-2b9ca88324cb"
                        },
                        new
                        {
                            UserId = "c145bd0d-9ff1-41ce-a54b-2756033b5233",
                            RoleId = "eea06f46-65c6-4b64-a57a-4e36d846c462"
                        },
                        new
                        {
                            UserId = "c145bd0d-9ff1-41ce-a54b-2756033b5233",
                            RoleId = "8bc01d01-b833-4304-bdda-10da6e453715"
                        },
                        new
                        {
                            UserId = "620b20af-c677-4632-81fb-0719f049d4d5",
                            RoleId = "eea06f46-65c6-4b64-a57a-4e36d846c462"
                        },
                        new
                        {
                            UserId = "620b20af-c677-4632-81fb-0719f049d4d5",
                            RoleId = "8bc01d01-b833-4304-bdda-10da6e453715"
                        },
                        new
                        {
                            UserId = "e6fca04f-0dd0-4990-b10f-0784cd05236c",
                            RoleId = "8bc01d01-b833-4304-bdda-10da6e453715"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SellSphere.Core.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"), 1L, 1);

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            ActivityName = "Приватний"
                        },
                        new
                        {
                            ActivityId = 2,
                            ActivityName = "Бізнес"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Тварини"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Електроніка"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Бізнес та послуги"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Хобі, відпочинок і спорт"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Дім та сад"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Дитячий світ"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Мода і стиль"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Condition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"), 1L, 1);

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConditionId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            ConditionId = 1,
                            ConditionName = "Новий"
                        },
                        new
                        {
                            ConditionId = 2,
                            ConditionName = "Б/У"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Contacts", b =>
                {
                    b.Property<int>("ContactsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactsId"), 1L, 1);

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactsId");

                    b.ToTable("Contactses");

                    b.HasData(
                        new
                        {
                            ContactsId = 1,
                            ContactPerson = "Іван Іванов Іванович",
                            EmailPerson = "ivan@sellsphere.com",
                            PhoneNumberPerson = "0681471239"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"), 1L, 1);

                    b.Property<string>("DeliveryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            DeliveryId = 1,
                            DeliveryName = "Нова Пошта"
                        },
                        new
                        {
                            DeliveryId = 2,
                            DeliveryName = "Укрпошта"
                        },
                        new
                        {
                            DeliveryId = 3,
                            DeliveryName = "Meest"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Goods", b =>
                {
                    b.Property<int>("GoodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsId"), 1L, 1);

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodIconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GoodsId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("ContactsId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Goodes");

                    b.HasData(
                        new
                        {
                            GoodsId = 1,
                            ActivityId = 1,
                            CategoryId = 2,
                            ConditionId = 2,
                            ContactsId = 1,
                            DeliveryId = 1,
                            Description = "ноутбук в гарному стані, є невеликі подряпини, екран не битий, 15.6 дюймів",
                            GoodIconPath = "\\Images\\acer.jpg",
                            GoodsName = "Ноутбук",
                            LocationId = 1,
                            Price = 35440,
                            PublicationDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "e6fca04f-0dd0-4990-b10f-0784cd05236c"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Чернігів"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Київ"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Луцьк"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Житомир"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Рівне"
                        });
                });

            modelBuilder.Entity("SellSphere.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c145bd0d-9ff1-41ce-a54b-2756033b5233",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a6f137b0-98db-4fbe-8bde-03f00532aba5",
                            Email = "admin@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SELLSPHERE.COM",
                            NormalizedUserName = "ADMIN@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEATAhb7anK/tFpo66PGerPhn1tYZ0Qa6aiHjLUZPbH+eRPOH1Rux4aYkHrajBzOzxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "964936bf-54df-4152-b51c-eac397343a0c",
                            TwoFactorEnabled = false,
                            UserName = "admin@sellsphere.com"
                        },
                        new
                        {
                            Id = "620b20af-c677-4632-81fb-0719f049d4d5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c072caf-80a7-4312-9ad0-a533ed14b0d7",
                            Email = "moder@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODER@SELLSPHERE.COM",
                            NormalizedUserName = "MODER@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENlVUu0KU/l6uVCsRvMG79TkAEMjgAxY7EvF3jmcwNGq9yI3gacMEnyI2gSLrlfDOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55e4207d-6275-4515-baa1-f8a8fd538793",
                            TwoFactorEnabled = false,
                            UserName = "moder@sellsphere.com"
                        },
                        new
                        {
                            Id = "e6fca04f-0dd0-4990-b10f-0784cd05236c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb84880c-e3c7-452c-ab00-0e298f686cba",
                            Email = "user@sellsphere.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@SELLSPHERE.COM",
                            NormalizedUserName = "USER@SELLSPHERE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEA4yqH1znagn8VbYUadEjdCm14DXIsHQ6KPwBs3E82VDWg/FY7kVVqKSyleYS1vmZg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f73d29b1-88f3-4028-b34c-cd96a65011d0",
                            TwoFactorEnabled = false,
                            UserName = "user@sellsphere.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SellSphere.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SellSphere.Core.Goods", b =>
                {
                    b.HasOne("SellSphere.Core.Activity", "Activity")
                        .WithMany("Goods")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Category", "Category")
                        .WithMany("Goods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Condition", "Condition")
                        .WithMany("Goods")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Contacts", "Contacts")
                        .WithMany("Goods")
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Delivery", "Delivery")
                        .WithMany("Goods")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.Location", "Location")
                        .WithMany("Goods")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SellSphere.Core.User", "User")
                        .WithMany("Goodes")
                        .HasForeignKey("UserId");

                    b.Navigation("Activity");

                    b.Navigation("Category");

                    b.Navigation("Condition");

                    b.Navigation("Contacts");

                    b.Navigation("Delivery");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SellSphere.Core.Activity", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Category", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Condition", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Contacts", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Delivery", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.Location", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("SellSphere.Core.User", b =>
                {
                    b.Navigation("Goodes");
                });
#pragma warning restore 612, 618
        }
    }
}
